name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Step 1: Install Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 2: Install Buildozer
      - name: Install Buildozer
        run: |
          pip install buildozer==1.5.0
          pip install Cython==0.29.33

      # Step 3: Build APK
      - name: Build APK
        run: |
          buildozer android debug

      # Step 4: Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: ./bin/*.apk
